### ISSUE TITLE
`Cipher.decrypt()` doesn't work

### ISSUE THREAD

**Issue by hammadmajid** [hammadmajid/caesar-cipher#29]
**Describe the bug**
When calling `Cipher.decrypt()`  programs return `null` despite the input

**To Reproduce**
1. run `java Main -d 1`
2. enter text when prompted

**Expected behavior**
shifted text

**Additional context**
version `1.0.0`

**Comment by Ztolpotato** [comment]
The null issues comes from 
public String cipherText; 
in Cipher.java
Change it to 
public String cipherText = "";
and you will remove the null issue. 
declaring a string with no value is automatically null.
